volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:
  changedetection_storage:
  redis_storage:
  nocode_storage:

networks:
  traefik:
    external: true

x-n8n: &service-n8n
  image: docker.io/kuo77122/n8n-python:latest
  networks: ['traefik']
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.n8n-http.entrypoints=web"
    - "traefik.http.routers.n8n-http.rule=(Host(`n8n.fattynan.com`))"
    - "traefik.http.routers.n8n-http.service=n8n-backend"
    - "traefik.http.services.n8n-backend.loadbalancer.server.scheme=http"
    - "traefik.http.services.n8n-backend.loadbalancer.server.port=5678"
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - GENERIC_TIMEZONE=Asia/Taipei
    - WEBHOOK_URL=https://n8n.fattynan.com
  links:
    - postgres

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: ['traefik']
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['traefik']
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull llama3.2"

services:
  postgres:
    image: postgres:16-alpine
    networks: ['traefik']
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - ./n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks: ['traefik']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    networks: ['traefik']
    volumes:
      - changedetection_storage:/datastore  # Main data volume
    environment:
      - PORT=20400  # Port for changedetection
      - PUID=0  # Running as root
      - PGID=0  # Running as root
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/chrome?token=${PLAYWRIGHT_TOKEN}&launch={"headless":false}  # WebSocket connection for Playwright
    ports:
      - 20400:20400  # Port mapping for changedetection
    restart: unless-stopped
    depends_on:
      - playwright-chrome

  playwright-chrome:
    hostname: playwright-chrome
    image: ghcr.io/browserless/chrome
    networks: ['traefik']
    restart: unless-stopped
    environment:
      - TOKEN=${PLAYWRIGHT_TOKEN}
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=true
      - TIMEOUT=600000
      - CONCURRENT=15
    ports:
      - 20450:3000  # Port mapping for Playwright WebSocket connection

  redis:
    image: redis:7.4.2-alpine
    restart: unless-stopped
    networks: ['traefik']
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --appendonly no --maxmemory 1024mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_storage:/data

  nocodb:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nocodb-http.entrypoints=web"
      - "traefik.http.routers.nocodb-http.rule=(Host(`nocodb.fattynan.com`))"
      - "traefik.http.routers.nocodb-http.service=nocodb-backend"
      - "traefik.http.services.nocodb-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.nocodb-backend.loadbalancer.server.port=8080"
    depends_on:
      postgres:
        condition: service_healthpostgresy
    environment:
      - NC_DB=pg://postgres:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}
      - NC_AUTH_JWT_SECRET=${NOCODB_JWT_SECRET}
      - NC_PUBLIC_URL=https://nocodb.fattynan.com
      - NC_DISABLE_TELE=true
    image: nocodb/nocodb:0.260.0
    networks: ['traefik']
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "nocode_storage:/usr/app/data"
